version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leave-management-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=leave_management
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    image: postgres:14-alpine
    container_name: leave-management-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leave_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: